preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:
  sonatype-oss-releases:
  rovo89-xposed-api:
    scope: LIBRARIES
    url: https://api.xposed.info/
    content:
      include:
        group:
          de.robv.android.xposed

plugins:
  com.android.application:
    alias: android-application
    version: 8.1.4
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 1.9.20
  com.google.devtools.ksp:
    alias: kotlin-ksp
    version: 1.9.20-1.0.14

libraries:
  de.robv.android.xposed:
    api:
      version: 82
      repositories:
        rovo89-xposed-api
  com.highcapable.yukihookapi:
    api:
      version: 1.2.0
    ksp-xposed:
      version-ref: <this>::api